### ISSUE TITLE
dataPreprocessing.m missing in Unmixing - Flow Cytometry

### ISSUE THREAD

**Issue by Saskia-vA** [djimenezsanchez/Blind_Unmixing_NMF_RI#1]
I tried running the main script in the "Unmixing - Flow Cytometry" folder. This leads to an error as the dataPreprocessing script is missing in this folder. I could find dataPreprocessing scripts in the other dataset folders, but these scripts differ from each other. I assume the Flow Cytometry data also requires its own data preprocessing steps. 

Can you add the dataPreprocessing script for Flow Cytometry data?

**Comment by djimenezsanchez** [comment]
Hello,

first of all, thanks for opening this issue.  dataPreprocessing in the "Unmixing - Flow Cytometry" script is interchangeable with the tissue cytometry dataset. 

I have uploaded the dataPreprocessing script for Flow Cytometry data.

Thanks.
